import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Lock, ShieldCheck } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api/v1';

export default function Checkout() {
  const { leadId } = useParams();
  const navigate = useNavigate();
  const [paymentData, setPaymentData] = useState(null);

  useEffect(() => {
    fetch(`${API_URL}/payment/intent`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ leadId, amount: 8990 })
    })
    .then(r => r.json())
    .then(d => {
      if(d.status === "success") setPaymentData(d.data);
    });
  }, [leadId]);

  return (
    <div className="max-w-md mx-auto py-20 text-center animate-fade-in relative z-10">
      <div className="w-24 h-24 bg-green-500/10 border border-green-500/30 text-green-400 rounded-full flex items-center justify-center mx-auto mb-8 shadow-[0_0_30px_rgba(74,222,128,0.2)]">
        <Lock size={40} className="drop-shadow-[0_0_8px_rgba(74,222,128,0.8)]" />
      </div>
      
      <h1 className="text-4xl font-black text-slate-100 tracking-tighter mb-4">Secure Gateway</h1>
      <p className="text-slate-400 font-medium tracking-wide mb-10">End-to-end encrypted protocol initiated for Contract <span className="text-cyan-400">#{leadId.slice(0, 8)}</span></p>

      {paymentData ? (
        <div className="glass-card p-10 rounded-3xl text-left border border-white/10 shadow-2xl relative overflow-hidden">
           
           <h3 className="text-xl font-black text-slate-100 tracking-wide mb-6 flex items-center justify-between border-b border-white/5 pb-4">
              Decentralized Invoice
              <ShieldCheck size={20} className="text-cyan-500" />
           </h3>
           
           <div className="space-y-4 text-sm font-medium">
             <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-xl border border-white/5">
               <span className="text-slate-500 tracking-widest uppercase text-[10px] font-bold">Ledger ID</span>
               <code className="text-cyan-400 px-2 py-1 bg-cyan-500/10 rounded">{paymentData.orderId}</code>
             </div>
             <div className="flex justify-between items-center bg-slate-900/50 p-3 rounded-xl border border-white/5">
               <span className="text-slate-500 tracking-widest uppercase text-[10px] font-bold">Protocol</span>
               <span className="text-slate-300 font-bold tracking-widest uppercase">{paymentData.gateway}</span>
             </div>
             
             <div className="pt-6 mt-6 border-t border-white/5 flex justify-between items-end">
               <span className="text-slate-500 tracking-widest uppercase text-xs font-bold">Total Execution</span>
               <span className="text-4xl font-black text-slate-100 tabular-nums tracking-tighter">
                 <span className="text-xl text-slate-500 mr-1 font-normal">₹</span>{paymentData.amount / 100}
               </span>
             </div>
           </div>
           
           <div className="mt-10">
             <button onClick={() => { alert('Mock Gateway Executed -> Output generated by: ' + paymentData.clientSecret); navigate('/'); }} className="w-full btn-glow text-white font-black py-5 rounded-2xl shadow-xl hover:-translate-y-1 transition text-lg tracking-widest uppercase text-xs">
               Authorize Capital Transfer
             </button>
           </div>
           
           <p className="text-center text-[10px] text-slate-600 font-bold uppercase tracking-widest mt-6">256-Bit SSL Encrypted Link</p>
        </div>
      ) : (
        <div className="flex flex-col items-center gap-4">
           <div className="w-12 h-12 border-4 border-cyan-500/20 border-t-cyan-500 animate-spin rounded-full"></div>
           <p className="text-cyan-400 font-bold tracking-widest text-xs uppercase animate-pulse drop-shadow-[0_0_5px_#22d3ee]">Handshaking Network...</p>
        </div>
      )}
    </div>
  );
}
